pagopa/pagopa-fdr-nodo-dei-pagamenti

helm/config/uat/config-app.conf, helm/weu-dev/values-dev.yaml, helm/weu-uat/values-uat.yaml
Change url to call Nexi services in UAT env
=> NOD-234: FDR allineare config-app ed helm per uat

.run/MainTest local.run.xml, build.sbt, fdr/src/main/resources/openapi_config.json, fdr/src/main/scala/eu/sia/pagopa/Main.scala, fdr/src/main/scala/eu/sia/pagopa/TestDData.scala, fdr/src/main/scala/eu/sia/pagopa/TestUtil.scala, fdr/src/main/scala/eu/sia/pagopa/common/message/ReMessage.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/Appfunction.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurestorageblob/AzureStorageBlobClient.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/soapinput/actor/SoapActorPerRequest.scala, fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala, helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, helm/fdr-cron/neu-dev/values-dev.yaml, helm/fdr-cron/weu-dev/values-dev.yaml, helm/fdr-cron/weu-prod/values-prod.yaml, helm/fdr/neu-dev/values-dev.yaml, helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-prod/values-prod.yaml, helm/fdr/weu-uat/values-uat.yaml, localresources/config-app.conf
=> feat: Nod 278 salvare su storage gli xml rendicontazioni

helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, localresources/config-app.conf
=> feat: NOD-299: Fix connection string blob storage

helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf
Changed value of **event-hub-name** props:
old: **nodo-dei-pagamenti-re-ndp**
new: **fdr-re**
=> feat: NOD-342: Fix eventhub name fdr

.devops/deploy-pipelines.yml
=> feat: fix deploy pipeline azure-pipeline-templates ref

helm/fdr-cron/weu-dev/values-dev.yaml, helm/fdr-cron/weu-uat/values-uat.yaml, helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-uat/values-uat.yaml
Change postgres flexible port from 5432 to 6432
=> feat: NOD-352: Cambiare porta postgres flexible fdrnodo

fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala
=> feat: NOD-403: fdrnodo salvataggio completo primitiva blobstorage

helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-prod/values-prod.yaml, helm/fdr/weu-uat/values-uat.yaml
=> feat: NOD-404: Nomi storageAccount senza env nel nome

fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala, helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, helm/fdr-cron/neu-dev/values-dev.yaml, helm/fdr-cron/weu-dev/values-dev.yaml, helm/fdr-cron/weu-prod/values-prod.yaml, helm/fdr-cron/weu-uat/values-uat.yaml, helm/fdr/neu-dev/values-dev.yaml, helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-prod/values-prod.yaml, helm/fdr/weu-uat/values-uat.yaml, localresources/config-app.conf
=> feat: Nod 407 validazione importo totale e somma dei pagamenti

helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, localresources/config-app.conf
=> feat: NOD-495: Cambiare connessione cache per FDR Fase 1

fdr/src/main/scala/eu/sia/pagopa/Main.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/ConfigUtil.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/Constant.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/DDataChecks.scala, fdr/src/main/scala/eu/sia/pagopa/config/actor/ApiConfigActor.scala, helm/config/dev/logback.xml, helm/config/prod/logback.xml, helm/config/uat/logback.xml, localresources/logback.xml
- E' stato corretto il logback.xml di dev per un errore nella formattazione del log su k8s
- Sono stati aggiuni i log per identificare quale fosse il numero della cache recuperata
- Fix su un controllo per il canale
=> feat: Nod 495 cambiare connessione cache per fdr fase 1

fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/GetXmlRendicontazioneResponse.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/DDataChecks.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/Util.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/GetAllRevisionFdrActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediElencoFlussiRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/restinput/actor/RestActorPerRequest.scala, fdr/src/test/resources/mocks/internalGetFdrPayment/KO.json, fdr/src/test/resources/mocks/internalGetFdrPayment/OK.json, fdr/src/test/resources/mocks/internalGetWithRevision/KO.json, fdr/src/test/resources/mocks/internalGetWithRevision/OK.json, fdr/src/test/scala/eu/sia/pagopa/ActorErrorUnitTests.scala, fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala, fdr/src/test/scala/eu/sia/pagopa/RestRendicontazioniTests.scala, fdr/src/test/scala/eu/sia/pagopa/testutil/TestDData.scala, fdr/src/test/scala/eu/sia/pagopa/testutil/TestUtil.scala
=> feat: NOD-508: [Fase 1] Troubleshooting dei test di integrazione

fdr/src/main/scala/eu/sia/pagopa/Main.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala, fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala, helm/fdr-cron/Chart.yaml, helm/fdr/Chart.yaml, openapi/openapi.json, version.sbt
NOD-519: Risposta PPT_SYSTEM_ERROR invio blob Azure
Aggiunto un UUID all'interno del fileName inviato su BlobStorage Azure, che essendo univoco, permette di salvare le sovrascrittura che potrebbero arrivare dai PSP e per i quali utilizzano sempre lo stesso idFlusso. 
Ogni volta che viene invocata la primitiva NodoInviaFlussoRendicontazione fdrnodo prima di rispondere invia su storage Azure il contenuto della chiamata del flusso di rendicontazione. Nel caso in cui venga inviato più volte lo stesso identificativo flusso, Azure restituisce 409 per identificativo duplicato. fdr gestisce questo come errore generico e restituisce al PSP PPT_SYSTEM_ERROR.
=> feat: NOD-519: Risposta PPT_SYSTEM_ERROR invio blob Azure

.devops/deploy-pipelines.yml
Aggiunto un parametro prima di lanciare la pipeline in modo da scegliere se sospendere i cornjob che gestiscono l'upload su FTP ed il suo retry.
E' stato aggiunta questa scelta poiché i FdR su FTP rimangono in gestione a Nexi e finché non si vorrà fare altro è inutile far partire dei pod e consumare risorse inutilmente nei vari ambienti.
=> feat: NOD-546: Disabilitare i cronjob fdr per gestione FTP

fdr/src/main/scala/eu/sia/pagopa/common/exception/DigitPaErrorCodes.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala, fdr/src/test/resources/mocks/nodoChiediFlussoRendicontazione/KO_nexi.xml
Cambiata la FAULT_STRING e la DESCRIPTION in caso di errore per Flusso sconosciuto
E' stata modificata per poter dare un messaggio meno fuorviante per gli EC che usano SFTP.
Run di tutti gli unit tests presenti nel progetto
=> feat: NOD-550: [FDR] Controllo per flusso su SFTP

.devops/deploy-pipelines.yml
=> Fix canary

helm/fdr/weu-prod/values-prod.yaml, helm/fdr/weu-uat/values-uat.yaml
=> feat: NOD-588: Utilizzo dns per raggiungere db per FDR

fdr/src/main/scala/eu/sia/pagopa/common/message/ReMessage.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/ReUtil.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/sdkazureclient/AzureProducerBuilder.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala, fdr/src/test/scala/eu/sia/pagopa/StaticUnitTests.scala
[NOD-687] (https://pagopa.atlassian.net/browse/NOD-687)
[NOD-687]: https://pagopa.atlassian.net/browse/NOD-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: NOD-687: Fdr fase 1 aggiungere eventi INTERNAL con status PUBLISHED

fdr/src/main/resources/json-schemas/notifyFlowRendicontazione.json, fdr/src/main/scala/eu/sia/pagopa/TestDData.scala, fdr/src/main/scala/eu/sia/pagopa/common/actor/HttpFdrServiceManagement.scala, fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/NotifyFdr.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/sdkazureclient/AzureProducerBuilder.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala, fdr/src/test/scala/eu/sia/pagopa/RestRendicontazioniTests.scala, helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, helm/fdr-cron/Chart.yaml, helm/fdr/Chart.yaml, localresources/config-app.conf, openapi/openapi.json, version.sbt
=> feat: NOD-687: Fdr fase 1 modifica notifyFlussoRendicontazione

fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/GenericResponse.scala, fdr/src/test/scala/eu/sia/pagopa/RestRendicontazioniTests.scala, helm/fdr-cron/Chart.yaml, helm/fdr/Chart.yaml, openapi/openapi.json, version.sbt
=> feat: Fix outcome notify

postman/FDR PAGOPA DEV.postman_environment.json, postman/FDR nodo.postman_collection.json
Updated postman collection and environment
=> Added postman collection and environment

common-xml/src/main/2.0/xsd/FlussoRiversamento_1_0_4.xsd
=> bugfix: NOD-803: [FDR Fase 1] Errore codice esito 4

.run/MainTest dev.run.xml, .run/MainTest local.run.xml, build.sbt, fdr/src/main/scala/eu/sia/pagopa/TestDData.scala, fdr/src/main/scala/eu/sia/pagopa/TestUtil.scala, fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FdRHistoryPaymentsRevision.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/Appfunction.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediElencoFlussiRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala, fdr/src/test/resources/mocks/internalGetFdrPayment/OK.json, fdr/src/test/scala/eu/sia/pagopa/ChecksUnitTests.scala, fdr/src/test/scala/eu/sia/pagopa/ConfigUnitTests.scala, fdr/src/test/scala/eu/sia/pagopa/FormatUnitTests.scala, fdr/src/test/scala/eu/sia/pagopa/MockserverExtension.scala, helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, helm/fdr-cron/Chart.yaml, helm/fdr/Chart.yaml, helm/fdr/neu-dev/values-dev.yaml, helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-prod/values-prod.yaml, helm/fdr/weu-uat/values-uat.yaml, localresources/config-app.conf, openapi/openapi.json, version.sbt
=> Nod 818 fdr anomalia recupero flussi nexi

common-xml/src/main/2.0/xsd/FlussoRiversamento_1_0_4.xsd, fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FdRHistoryPaymentsRevision.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala
=> feat: NOD-867: [FDR] Aggiunta codice esito pagamento 8

helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, helm/fdr-cron/Chart.yaml, helm/fdr/Chart.yaml, helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-uat/values-uat.yaml, openapi/openapi.json, version.sbt
=> fix: [PTPO-208] Set PostgreSQL cache

.github/workflows/00_anchore.yml, .github/workflows/03_code_review.yml, fdr/src/main/scala/eu/sia/pagopa/Main.scala, fdr/src/main/scala/eu/sia/pagopa/common/json/model/TransactionEvent.scala, fdr/src/main/scala/eu/sia/pagopa/common/repo/fdr/model/Rendicontazione.scala, fdr/src/main/scala/eu/sia/pagopa/common/repo/fdr/table/RendicontazioneTable.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/ConfigUtil.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/Constant.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/EventUtil.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/Appfunction.scala, fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/sdkazureclient/AzureProducerBuilder.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/BaseFlussiRendicontazioneActor.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala, fdr/src/test/scala/eu/sia/pagopa/StaticUnitTests.scala, helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, helm/fdr/neu-dev/values-dev.yaml, helm/fdr/weu-dev/values-dev.yaml, helm/fdr/weu-prod/values-prod.yaml, helm/fdr/weu-uat/values-uat.yaml, localresources/config-app.conf
=> feat: NOD-840 riversamento su event hub per qi

helm/config/dev/config-app.conf, helm/config/prod/config-app.conf, helm/config/uat/config-app.conf, localresources/config-app.conf
=> feat: fix env deploy

helm-fdr/helm/values-prod.yaml
=> chore: fix chart

build.sbt, helm-cron/helm/values-dev.yaml, helm-cron/helm/values-prod.yaml, helm-cron/helm/values-uat.yaml, helm-fdr/helm/Chart.yaml, helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml, openapi/openapi.json, version.sbt
=> chore: Fix helm dev + app insight

fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala, helm-fdr/helm/Chart.yaml, helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml, openapi/openapi.json, version.sbt
=> chore: HotFix nodoChiediFlussoRendicontazione

.devops/performance-test-pipelines.yaml, .github/workflows/07_performance_test.yml, performance-test/src/environments/uat.environment.json, performance-test/src/nodoChiediElencoFlussiRendicontazione_scenario.js, performance-test/src/nodoChiediFlussoRendicontazione_scenario.js, performance-test/src/only_nodoInviaFlussoRendicontazione_payments_ramp_scenario.js, performance-test/src/only_nodoInviaFlussoRendicontazione_scenario.js, performance-test/src/only_nodoInviaFlussoRendicontazione_scenario_5k150k.js, performance-test/src/only_nodoInviaFlussoRendicontazione_scenario_5k50k.js, performance-test/src/test-types/constant.json
Update input gh action and values inside pipeline
Needed in order to launch different tests without always adding them
Manually
=> Fix input gh

helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml
=> chore: Fix JAVA_OPTS and scaling config

helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml
=> chore: Fix memory

.devops/performance-test-pipelines.yaml, performance-test/src/only_nodoInviaFlussoRendicontazione_scenario_soak.js, performance-test/src/test-types/constantSoak.json, performance-test/src/test-types/constant_nodoChiediElencoFlussi.json, performance-test/src/test-types/constant_nodoChiediFlusso.json
Adding soak testing option in the performance test folder
Needed in order to provide a soak test for NodoInviaFlussoRendicontazione
Manually through k6
=> Pagopa 2643 fdr 1 soak testing

.gitignore, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml
=> feat: Tuning deploy prod-cfg

utils/rendicontazione_insert.py
Utils script to save data on `rendicontazione` table from a CSV called `rendicontazione.csv`
=> chore: [PAGOPA-2669] Script to insert data in rendicontazione table

fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NodoInviaFlussoRendicontazioneFTPActor.scala, helm-fdr/helm/config/prod/logback.xml, helm-fdr/helm/config/uat/logback.xml
=> fix: reducing logs for some primitives

infra/psql/liquibase/changelog/1.0.2/db.changelog-20250227000000_fix-varchar.xml, infra/psql/liquibase/changelog/db.changelog-master-1.0.2.xml
=> [PAGOPA-2702] feat(liquidbase): Replace indexes

helm-fdr/helm/values-prod.yaml
- the liveliness and readiness _periods_ and _initialDelay_ were extended
The problem solved is the timeout on liveness during rollout. Specifically there is an **_unbinding http server_** because the app doesn't run _**Starting HTTP Service (Seed, Soap, Rest)..**_. phase
=> [PAGOPA-2268] ci(helm): Update liveness config

.devops/fdr-db-schema-pipelines.yml
Create new read user for FDR1 according to https://pagopa.atlassian.net/wiki/x/toBuWw
=> chore: Add `fdr1r` user read 4 SMO

.github/workflows/07_performance_test.yml, integration-test/config/uat.json, integration-test/run_test.sh, performance-test/src/environments/dev.environment.json, performance-test/src/environments/local.environment.json, performance-test/src/environments/uat.environment.json, performance-test/src/happy_case_scenario.js
- fix integration test fdr
- change the field type of perf. test: script-name, test-type from string to choice (gh action)
The intervention fix an issue with the integration tests caused by a failing command. It also updates the PSP/creditor entity used in the integration tests, as the previous ones were too heavy and were causing test failures due to excessive call durations.
Integration test / Performance test
=> [PIDM-330] fix: Integration test FDR

fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala, helm-cron/helm/values-dev.yaml, helm-cron/helm/values-prod.yaml, helm-cron/helm/values-uat.yaml, helm-fdr/helm/Chart.yaml, helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml, localresources/config-app.conf, openapi/openapi.json, version.sbt
=> fix(helm-fdr): update ingress path for production, UAT, and dev environments

integration-test/config/uat.json, integration-test/features/complete_flow.feature, integration-test/steps/steps.py
=> fix: uat integration test configuration

utils/base64.js, utils/chunked.sh, utils/nodoInviaFlussoRendicontazione.sh
-changed POST_URL endpoint
-script argument fix
[PAGOPA-2716](https://pagopa.atlassian.net/browse/PAGOPA-2716) 
[PAGOPA-2716] : https://pagopa.atlassian.net/jira/software/c/projects/PAGOPA/boards/336?selectedIssue=PAGOPA-2716
[PAGOPA-2716]: https://pagopa.atlassian.net/browse/PAGOPA-2716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PAGOPA-2716]: https://pagopa.atlassian.net/browse/PAGOPA-2716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [PAGOPA-2716] changed POST_URL endpoint

fdr/src/main/resources/json-schemas/convertFlowRendicontazione.json, fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/Flow.scala, fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FlowPayment.scala, fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/ConvertFlussoRendicontazioneActorPerRequest.scala, helm-fdr/helm/Chart.yaml, helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml, openapi/openapi.json, version.sbt
- Update mapping payment amounts
[PAGOPA-2978](https://pagopa.atlassian.net/browse/PAGOPA-2978)
expected)
[PAGOPA-2978]: https://pagopa.atlassian.net/browse/PAGOPA-2978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [PAGOPA-2978] Resolving payment amounts types in decimal values

helm-fdr/helm/config/dev/config-app.conf, helm-fdr/helm/config/prod/config-app.conf, helm-fdr/helm/config/uat/config-app.conf, helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml, localresources/config-app.conf
=> chore: [PAGOPA-2872] Configuration housekeeping

fdr/src/main/scala/eu/sia/pagopa/common/message/ReMessage.scala, fdr/src/main/scala/eu/sia/pagopa/common/repo/re/model/Fdr1Metadata.scala, helm-fdr/helm/Chart.yaml, helm-fdr/helm/values-dev.yaml, helm-fdr/helm/values-prod.yaml, helm-fdr/helm/values-uat.yaml, openapi/openapi.json, version.sbt
=> fix: [PAGOPA-2696] Including `PartitionKey` fields in MongoDB documents

infra/psql/liquibase/changelog/1.0.3/db.changelog-20251001000000_create-index.xml, infra/psql/liquibase/changelog/db.changelog-master-1.0.3.xml
- updated liquidbase to add 2 more index on table `rendicontazione` for colum `dominio`-`data_ora_flusso` and `psp`-`data_ora_flusso`
[PIDM-1036](https://pagopa.atlassian.net/browse/PIDM-1036)
Added new index on table `rendicontazione` to improve query performance
[PIDM-1036]: https://pagopa.atlassian.net/browse/PIDM-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PIDM-1036] chore: Add new database index on table rendicontazione
